name: Build, Test, Deploy
on:
  workflow_dispatch:
  push:
    branches:
    - "3-cicd"

jobs:
  build-and-test:
    name: Build & Test Image
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.docker_hub_username }} -p ${{ secrets.docker_hub_password }}

    - name: Build Image
      run: docker build -t ${{ secrets.docker_hub_username }}/bitcoin-core:22.0 ./1-Docker/

    - name: Upload Image
      run: docker push ${{ secrets.docker_hub_username }}/bitcoin-core:22.0

    - name: Install Syft
      run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Install Grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate Syft SBOM
      run: syft ${{ secrets.docker_hub_username }}/bitcoin-core:22.0 -o json > image.json

    - name: Scan SBOM with grype
      run: grype sbom:image.json

  deploy:
    name: Deploy to k8s
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install kubectl
      run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

    - name: Install datree
      run: curl https://get.datree.io | /bin/bash

    - name: Login datree
      run: datree config set token ${{ secrets.datree_token }}

    - name: Test manifest
      run: datree test ./2-k8s/deploy.yaml

    - name: Apply manifest
      run: kubectl --kubeconfig ${{ secrets.kubeconfig }} apply -f ./2-k8s/deploy.yaml --namespace default
