name: Build, Test, Deploy
on:
  workflow_dispatch:

jobs:
  build-image:
    name: Build & Test Image
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.docker_hub_username }} -p ${{ secrets.docker_hub_password }}

    - name: Build Image
      run: docker build -t ${{ secrets.docker_hub_username }}/bitcoin-core:22.0 ./1-Docker/

    - name: Upload Image
      run: docker push ${{ secrets.docker_hub_username }}/bitcoin-core:22.0

    - name: Install Syft
      run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Install Grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generage Syft SBOM
      run: syft ${{ secrets.docker_hub_username }}/bitcoin-core:22.0 -o json > image.json

    - name: Generage Syft SBOM
      run: grype sbom:image.json

        #deploy:
        #  name: Deploy to k8s
        #  runs-on: ubuntu-latest

        #  steps:
        #  - name: Apply manifest
        #    run: kubectl apply -f ./2-k8s/deployment.yaml
